### ISSUE TITLE
Validation keeps failing

### ISSUE THREAD

**Issue by jguittard** [basselin/zf2-new-recaptcha#1]
Basic / straight integration of the element in a Zend\Form.
Display correctly in the view, validation from Google OK.
Upon form submission (PRG), form validation fails with:
`'missingValue' => string 'Missing captcha fields'`

Digging... 

In https://github.com/basselin/zf2-new-recaptcha/blob/master/src/NewReCaptcha/Validator/NewReCaptcha.php#L106, injected request from the factory in https://github.com/basselin/zf2-new-recaptcha/blob/master/src/NewReCaptcha/Form/Element/Service/NewReCaptchaFactory.php#L39 comes from the first GET request. 

Therefore, https://github.com/basselin/zf2-new-recaptcha/blob/master/src/NewReCaptcha/Validator/NewReCaptcha.php#L107 will always evaluate to `false`

Unit tests don't test the validator.

**Comment by basselin** [comment]
Could you show me your class Form ?
Which name do you use for this element ?

**Comment by jguittard** [comment]
in my form class `init()` method:
`$this->add([
            'name' => 'captcha',
            'type' => 'newReCaptcha',
            'options' => [
                'site_key'   => 'XXXXXX',
                'secret_key' => 'XXXXXX',
            ]
        ]);`

**Comment by basselin** [comment]
You can try to put your `site_key` and `secret_key` in autoload config :

``` php
    'new_recaptcha' => [
        'site_key'   => '...',
        'secret_key' => '...',
    ],
```

Could you show me your phtml file ?

``` php
    <div class="form-group"><?= $this->formNewReCaptcha($form->get('captcha')) ?></div>
```

Do you use any filter or validator in your `InputFilter` ? Because it is useless.

**Comment by basselin** [comment]
You can try the last version.
